version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: sh -c "python3 bot/bot.py & python3 -m http.server 8080"
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
