version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: >
      sh -c "
      echo 'Starting bot...' &&
      python3 bot/bot.py &
      echo 'Starting HTTP server...' &&
      while true; do
        python3 -m http.server 8080 --bind 0.0.0.0
        sleep 1
      done
      "
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
