version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build: .
    ports:
      - "8080:8080"
    extra_hosts:
      - "managed-410815-5699231:192.168.0.4"
    # Добавьте для диагностики
    environment:
      - PYTHONUNBUFFERED=1
