version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: tail -f /dev/null
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
